export const WORDS = [
    "Mike is the best",
    "Abbey is the best",
    "Paulo is the best",
    "I like sushi",
    "destroy me",
    "let me live T_T",
    "yum lunch",
    "let it rip",
    "slime slime slime",
    "what is love?",
    "baby don't hurt me",
    "Ew! A pink rabbit!",
    "do or do not",
    "roses are red",
    "coding is cool",
    "find the One Piece",
    "drill pierce heavens!",
    "ask salmon else",
    "slime slime slime",
    "krusty krab pizza",
    "UwU",
    "plus ultra",
    "I'm gonna be hokage!",
    "yer a wizard, bunny",
    "slimes not limes",
    "dedicate your heart",
    "time stops for no one",
    "yum yum",
    "rise and slime",
    "slime this",
    "is purple a shade of blue?",
    "are you a bully?",
    "hike and brunch",
    "don't mock me",
    "slimes be sliming",
    "it be like that sometimes",
    "drink water",
    "hello world",
    "i am goo-tiful",
    "stay gooey",
    "you're kinda goo-fy",
    "slime feelin' good",
    "blue over pink",
    "SQUISHY",
    "squish this",
    "WOW BUNNY",
    "8==D",
    "1, 2, 3, 4",
    "wherever, whenever",
    "Who am I?",
    "what am I?",
    "I'm just filler",
    "woohoo, WOOHOO",
    "all because of a snail...",
    "I wanna digivolve.",
    "the first rule of slime club...",
    "I wanna be the very best",
    "baby, don't hurt me",
    "shake it off",
    "keep calm",
    "champagne",
    "vanilla extract",
    "Rose Water",
    "sora, riku, kairi",
    "brave new world",
    "a thousand splendid slimes",
    "life-changing magic of slime",
    "come along with me",
    "Come here.",
    "crying in slime mart",
    "wash your hands",
    "boba is life",
    "ball is life",
    "Octopuses or octopodes?"
]

