export const WORDS = [
    "Mike is the best",
    "Abbey is the best",
    "Paulo is the best",
    "I like sushi",
    "destroy me",
    "let me live T_T",
    "yum lunch",
    "let it rip",
    "slime slime slime",
    "what is love?",
    "baby don't hurt me",
    "Ew!",
    "do or do not",
    "roses are red",
    "coding is cool",
    "find the One Piece",
    "drill pierce heavens!",
    "ask salmon else",
    "slime slime slime",
    "krusty krab pizza",
    "UwU",
    "plus ultra",
    "me hokage!",
    "yer a wizard, bunny",
    "slimes not limes",
    "dedicate your heart",
    "time stops for no one",
    "yum yum",
    "rise and slime",
    "slime this",
    "is purple blue?",
    "are you a bully?",
    "hike and brunch",
    "don't mock me",
    "slimes be sliming",
    "it be like that",
    "drink water",
    "hello world",
    "i am goo-tiful",
    "stay gooey",
    "you're kinda goo-fy",
    "slime feelin' good",
    "blue over pink",
    "SQUISHY",
    "squish this",
    "WOW BUNNY",
    "8==D",
    "1, 2, 3, 4",
    "wherever, whenever",
    "Who am I?",
    "what am I?",
    "I'm just filler",
    "woohoo, WOOHOO",
    "snails have slime",
    "I wanna digivolve.",
    "smile",
    "I wanna be the very best",
    "baby, don't hurt me",
    "shake it off",
    "keep calm",
    "champagne",
    "vanilla extract",
    "Rose Water",
    "2 + 2 = 5",
    "brave new world",
    "splendid slimes",
    "gobble",
    "come along with me",
    "Come here.",
    "crying in slime mart",
    "wash your hands",
    "boba is life",
    "ball is life",
    "octopus"
]

